### ISSUE TITLE
Upstream request about callee-saved registers

### ISSUE THREAD

**Issue by fw-brice** [riscv-collab/v8#489]
Review comment from Michael on our [initial upstreaming review](https://chromium-review.googlesource.com/c/v8/v8/+/2571344):

> src/heap/base/asm/riscv64/push_registers_asm.cc:10
> Michael Lippautz
> Patchset 20
> Apr 19
> Sorry for being late here, only saw that file now in our tree.
>
> Can we add a link to some docs where the callee-saved registers are defined.
>
> We've had problems in the past that this was undocumented which made it really hard for us to modernize code for other platforms.

We can add a link in the comments to the [spec](https://github.com/riscv/riscv-isa-manual/releases/download/Ratified-IMAFDQC/riscv-spec-20191213.pdf) and a pointer to chapter 25. However, when I looked at this, I do not see all of the callee saved registers being saved (s9-11, are not included), and `gp` is included, which is not identified as callee-saved. I do not remember a reason for this. Does anyone remember why there is this discrepancy?

**Comment by qjivy** [comment]
It seems coming from 'src/heap/base/asm/mips64/push_registers_asm.cc'. 

Since mips64  in N64/N32 has s0-s7 for callee save register set, but RISC-V has s0~s11, so we need to add  s9,s10,s11 to this code snippet. 

Meanwhile,  the 'gp,fp(s8),sp,ra' in MIPS64 are saved because this funcion is just like a function prologue to preparing for the calling of 'IteratePointersImpl' in 'src/base/stack.cc'.

**Comment by qjivy** [comment]
Finished this issue on  https://chromium-review.googlesource.com/c/v8/v8/+/2848476 .

Close.
